class_weight: balanced
features:
- Ingresos
- Gastos
- Activos
- Pasivos
- EBIT
- ROA
- ROE
- Margen_Explotacion
- Endeudamiento
- Indice_Rentabilidad
- Plantilla
- Costes_Fijos
- CostesVariables
- Crecimiento_Ingresos
- Ingresos_por_Empleado
- Ratio_Gastos_Ingresos
- Margen_Operativo
- Solvencia
- Costes_Totales
- Peso_Costes_Fijos
kernel: rbf
model_name: SVM
random_state: 42
scaler: StandardScaler
test_size: 209
train_size: 832
